name: hoamlCI
on:
  push:
    branches: [ dev ]
jobs:
    PullAndRunDockerInServer:
      runs-on: ubuntu-latest
      steps:
        - name: ls -a via ssh
          uses: fifsky/ssh-action@master
          with:
            command: |
              git checkout dev
            host: ${{ secrets.SSH_HOST }}
            user: ${{ secrets.SSH_USER }}
            pass: ${{ secrets.SSH_PASSWORD}}
            args: "-tt -vvv"
